name = "vegas-herobet-pl"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=vegas-herobet.pl"
HMAC_KEY = "dac1b8f5f972c487e12e6c2ac96426f5287b5a0db8588ba142faa568253b75ae"
COOKIE_NAME = "6yj"
PLAY_PATH = "start"
BUTTON_ID = "p38f919c72e9d88c395047505ddb5ee47"
GATE_SALT = "e28617ca104fcea1"
