name = "vegas-herobet-pl"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=vegas-herobet.pl"
HMAC_KEY = "dac1b8f5f972c487e12e6c2ac96426f5287b5a0db8588ba142faa568253b75ae"
COOKIE_NAME = "hju"
PLAY_PATH = "begin"
BUTTON_ID = "p38f919c72e9d88c395047505ddb5ee47"
GATE_SALT = "770ef674e9b9728f"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "z8zq"
CTA_SELECTOR = ".play-button"
